[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_token_financing = "HtqUGmzuqaRD4naSAG9qH4T23B8454ZeyZp33UF9wSrU"

[programs.localnet]
solana_token_financing = "HtqUGmzuqaRD4naSAG9qH4T23B8454ZeyZp33UF9wSrU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "accounts/id.json"
# cluster = "Devnet"
# wallet = "accounts/nemeos.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 9100000000 tests/**/*.ts"
