[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_token_financing = "EwHaqQucKCZi7Yxwj454QM9MR4gFg3zspmZp3bNwKBwF"

[programs.localnet]
solana_token_financing = "EwHaqQucKCZi7Yxwj454QM9MR4gFg3zspmZp3bNwKBwF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "accounts/id.json"
# cluster = "devnet"
# wallet = "accounts/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
